  const BASE_URL = "http://127.0.0.1:8000";
  // const BASE_URL = "https://smartbakery.nubifysoftware.com";
  // const BASE_URL = "https://smartbakerytest.nubifysoftware.com";

  const Endpoint = {
    Login: `${BASE_URL}/api/auth/login`,
    Register: `${BASE_URL}/api/auth/register`,
    AddToken: `${BASE_URL}/api/addToken`,
    ProductList: `${BASE_URL}/api/products/getData`,
    AddProduct: `${BASE_URL}/api/products/addProduct`,
    ProductDelete: `${BASE_URL}/api/products/productDelete`,
    StockParams: `${BASE_URL}/api/stocks/getParam`,
    WeatherItem: `${BASE_URL}/api/stocks/getWeatherItem`,
    AddStock: `${BASE_URL}/api/stocks/saveStock`,
    StockData: `${BASE_URL}/api/stocks/getStockData`,
    StockDelete: `${BASE_URL}/api/stocks/stockDelete`,
    EndOfDayListData: `${BASE_URL}/api/endofdays/getEndOfListData`,
    EndOfDayAdd: `${BASE_URL}/api/endofdays/addEndOfData`,
    EndOfCheck: `${BASE_URL}/api/endofdays/endOfDataCheck`,
    EndOfData: `${BASE_URL}/api/endofdays/getEndOfData`,
    EndOfDelete: `${BASE_URL}/api/endofdays/delete`,
    ReportData: `${BASE_URL}/api/reports/getReportData`,
    ReportSend: `${BASE_URL}/api/reports/createReport`,
    GuessData: `${BASE_URL}/api/guess/getData`,
    GuessMail: `${BASE_URL}/api/guess/totalGuessPdfMail`,
    UpdateProfile: `${BASE_URL}/api/profile/updateProfile`,
    UpdatePassword: `${BASE_URL}/api/profile/updatePassword`,
    GetProfileData: `${BASE_URL}/api/profile/getProfileData`,
    AddUser: `${BASE_URL}/api/users/addUser`,
    GetUsers: `${BASE_URL}/api/users/getUsers`,
    GetWaitData: `${BASE_URL}/api/users/getWaitData`,
    ApproveUser: `${BASE_URL}/api/users/approve`,
    GetCompanyInfo: `${BASE_URL}/api/company/getData`,
    SaveSettings: `${BASE_URL}/api/company/save`,
    ReinstallStart: `${BASE_URL}/api/reinstall/start`,
    UserChange: `${BASE_URL}/api/user/userChange`,  
    FreezerList: `${BASE_URL}/api/freezer/getData`,
    FreeSave: `${BASE_URL}/api/freezer/save`,
    FreeDelete: `${BASE_URL}/api/freezer/delete`,
    FreeReportSend: `${BASE_URL}/api/freezer/createReport`,
    LastStockData: `${BASE_URL}/api/laststock/getData`,
    LastStockSave: `${BASE_URL}/api/laststock/save`,
    HolidayData: `${BASE_URL}/api/holidays/getData`,
    HolidayAdd: `${BASE_URL}/api/holidays/add`,
    HolidayDelete: `${BASE_URL}/api/holidays/delete`,
    CustomOrderData: `${BASE_URL}/api/customorders/getCustomOrders`,
    CustomOrderAdd: `${BASE_URL}/api/customorders/add`,
    CustomOrderDelete: `${BASE_URL}/api/customorders/delete`,
    CustomOrderReportData: `${BASE_URL}/api/customordersReport/getReportData`,
    CustomOrderReportSend: `${BASE_URL}/api/customordersReport/createReportMail`,
    ReportViewChange: `${BASE_URL}/api/reports/reportViewChange`,
    FreezerDefList: `${BASE_URL}/api/freezerdef/getData`,
    FreezerDefSave: `${BASE_URL}/api/freezerdef/save`,
    FreezerDefDelete: `${BASE_URL}/api/freezerdef/delete`,
  };

  export default Endpoint;